### ISSUE TITLE
I would like to have a /coffee command to order a coffee

### ISSUE THREAD

**Issue by ErikApption** [Turtlebot-Discord/slash-commands#15]
- /coffee with COFFEE emoji
- Connect to the starbucks or bridgehead API
- Ask for payment
- Get coffee delivered

**Comment by ErikApption** [comment]
also I don't see how to order a coffe without a /coffee command? Is there a workaround?

**Comment by TurtlePaw** [comment]
> also I don't see how to order a coffe without a /coffee command? Is there a workaround?

You could order on the bridgehead site or starbucks site

**Comment by ErikApption** [comment]
anyway I don't understand why a bot wouldn't have a /coffee command, it is the most requested feature in the most recent discord bot survey
